### ISSUE TITLE
First 4 Encoders doesn't work

### ISSUE THREAD

**Issue by mojo6666** [YamanCool/Ableton_Live11_MIDI_RemoteScripts#1]
All work fine with Ableton 11 but with the joggle encoder 3 function to pan with the encoder doesn't work ... Do you know how to Pan with the encoder ?? i cant figuar it out ... need help

**Comment by YamanCool** [comment]
In assignment mode Volume/Pan you can turn the knobs (1 to 8) for panning and the sliders (1 to 8) are for the track volume.

**Comment by mojo6666** [comment]
hey thanks YamanCool for answering after so long time :) yeah it doesnt work how you can get in the Assignment mode ? Press jogweel =? i have the same problem like the guy in in ableton forum ? all work but what should i press to get in the assignment mode ? thanks man !

**Comment by YamanCool** [comment]
Press the Jog Wheel Button **and** the corresponding knob. Read also the manual.

**Comment by mojo6666** [comment]
yeah but it doesnt work ... as i said :((( when i press the jog wheel for the other functions for example switch to the send (jogwheel+ 7 encoder this work... or jogwhhel press select 8 for undo etc. but when  i press Jogwheel and encoder 3 for panning nothing happpend ... maybe it would help also uploading the .imap templet from the icon software ?

**Comment by mojo6666** [comment]
ok i think i have the answer... i deleted complet ableton and reinstalled it i had the trial version and got the full version from ableton. and now it works ? super strange ... thanks again for you super work !

**Comment by YamanCool** [comment]
Thanks
